### ISSUE TITLE
entropy coding？

### ISSUE THREAD

**Issue by liujiawei2333** [adityassrana/Content-Weighted-Image-Compression#1]
Thanks for the code! I want to ask how is the entropy coding stage done? I did not understand the entropy coding part of the original paper. I don’t see this part in your code either.

**Comment by adityassrana** [comment]
Hi Liu, you can use arithmetic encoding or CABAC implementations available publicly. I did not implement the convolutional entropy encoder mentioned in the paper. I compared my results by calculating the upper limit on the compression rate(bpp) from the importance map.
